name: Build and Pack and Push to Nuget on version update

on:
  push:
    branches: 
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Restore NuGet Packages
        run: dotnet restore ClientSdk.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and Pack Solution
        run: msbuild ClientSdk.sln /t:pack /p:Configuration=Release

      - name: Run Tests
        run: dotnet test ClientSdk.sln --no-restore

      - name: Publish the package to nuget.org when we have a new version
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
        run: |
          $version = (Select-Xml -Path .\src\Directory.Build.props -XPath /Project/PropertyGroup/Version).Node.InnerText
          $versions = (Invoke-WebRequest https://api.nuget.org/v3-flatcontainer/ExactOnline.Client.Sdk.vNext/index.json -UseBasicParsing | ConvertFrom-Json).versions
          if (-not($versions -contains $version)) {
            dotnet nuget push .\src\*.nupkg -k $env:NUGET_AUTH_TOKEN
          }
