name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for the master and the v3.3 branches
  push:
    branches: 
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Restore NuGet Packages
        run: dotnet restore ClientSdk.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and Pack Solution
        run: msbuild ClientSdk.sln /t:pack /p:Configuration=Release

      - name: Run Tests
        run: dotnet test ClientSdk.sln --no-restore

      - name: Publish the package to nuget.org
        run: dotnet nuget push *.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
